# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XJYChartDemo' do
  use_frameworks!

pod ‘Masonry’


end

target 'XJYChartDemo-Swift' do

  use_frameworks!



end
